### ISSUE TITLE
api返回参数

### ISSUE THREAD

**Issue by youngsun45** [freakchick/DBApi#14]
建议返回头参数配置，比如返回头中要求有status,msg等格式如下：
{
  "status": 0,
  "msg": "",
  "data": {
    ...其他字段
  }
}
可在返回头中添加任意自己要求的字段

这样可以适配更多的客户端，满足不同的需求。

**Comment by freakchick** [comment]
只有客户端去适配服务端，哪有服务端适配客户端

**Comment by anyint96** [comment]
@freakchick 作者，你好，我也认为这个api返回参数自定义的功能有必要，比如layui的table组件，需要返回的就是一楼发的那种数据样式，新增此功能会让dbapi更加实用。

**Comment by freakchick** [comment]
4.0.0 全局数据转换插件已经实现
