### ISSUE TITLE
是否有办法完成SQL的校验工作

### ISSUE THREAD

**Issue by zijian666** [freakchick/DBApi#28]
假设配置sql的功能提供给专业用户使用, 但又想校验sql是否安全
可以自己写校验规则, 执行前或执行后提交事务前校验, 如果不符合规则就报错
目前的插件是否可以完成这样的工作?

场景1, 校验 sql中不允许使用左like语句  在执行前分析sql 存在左like则报错
场景2, 校验sql执行后受影响行数,超过1000行则报错 回滚
场景3, 执行前设置超时时间, 执行超过5秒则报错回滚

**Comment by freakchick** [comment]
这些场景不通用，建议使用  [dbApi-spring-boot-starter](https://github.com/freakchick/dbApi-spring-boot-starter)
