### ISSUE TITLE
app分配分组API后，查询不到已分配状态

### ISSUE THREAD

**Issue by dingchao111** [freakchick/DBApi#30]
![image](https://user-images.githubusercontent.com/87065618/208379381-9d6b3c18-74be-4a58-b548-0f68a2f47dfd.png)
如图所示
1. 已经给app “test” 分配了分组的API “test_token”
2. 在刷新页面，或重新打开页面后，再点操作按钮，已分配的分组API 复选框没有标记勾上

**Comment by freakchick** [comment]
已在3.2.1版本修复
