### ISSUE TITLE
插入多条数据时数值字段无法插入空值

### ISSUE THREAD

**Issue by GodHunter2022** [freakchick/DBApi#40]
使用application/json方式，进行多数据上传

sql代码如下：
insert into fishfeed3(超级账户,入池停食天数) VALUES
<foreach open="" close="" collection="fishfeed3" separator="," item="item" index="index">
(#{item.超级账户}, #{item.入池停食天数})
</foreach>

使用以下参数时可以正常上传：
{"fishfeed3":[{"超级账户":"B","入池停食天数":3}]}

但是，如果想要上传一个"入池停食天数"是空值的数据时，以下代码均无效
方式一参数  {"fishfeed3":[{"超级账户":"B"}]} 
方式一错误提示：java.lang.RuntimeException: java.lang.RuntimeException: could not found value : fishfeed3[0].入池停食天数
方式二参数 {"fishfeed3":[{"超级账户":"B","入池停食天数":null}]}
方式一错误提示：java.lang.RuntimeException: java.lang.RuntimeException: could not found value : fishfeed3[0].入池停食天数

数据库使用的mysql，操作系统是windows， "超级账户"字段是varchar(20)不允许空值,"入池停食天数"字段是int,允许空值
以下是Mysql中创建表的sql

**Comment by GodHunter2022** [comment]
以下是Mysql中创建表的sql

create table FishFeed3(
超级账户 nvarchar(20) not null,
入池停食天数 int
);

**Comment by GodHunter2022** [comment]
insert into fishfeed3(超级账户,入池停食天数) VALUES
<foreach open="" close="" collection="fishfeed3" separator="," item="item" index="index">
(#{item.超级账户}, #{item.入池停食天数})
</foreach>

**Comment by GodHunter2022** [comment]
API中的sql语句如下
![1681564070033](https://user-images.githubusercontent.com/108559430/232225695-2802debd-0403-4495-ad07-8b9738caa7c4.jpg)

**Comment by freakchick** [comment]
为什么要用中文字段，会有很多问题
