### ISSUE TITLE
4.0版本在数据源不通的情况下，访问API后会导致页面打开空白，无法加载内容，必须等待做所有的请求都超时后才能打开页面

### ISSUE THREAD

**Issue by songxw** [freakchick/DBApi#46]
大量请求等待中
![image](https://github.com/freakchick/DBApi/assets/4016475/818ccc2e-3d91-4545-aa0b-8d5aacda24cb)
业务打开空白
![image](https://github.com/freakchick/DBApi/assets/4016475/fa3633a3-4e30-4a6a-ae78-770dbb2c0ad5)
全部请求超时后页面能打开
![image](https://github.com/freakchick/DBApi/assets/4016475/e8ea1c80-a255-46f3-95c3-2372613ec429)
![image](https://github.com/freakchick/DBApi/assets/4016475/b52b3f2d-be3a-4873-a2fb-73e3480d19f7)

**Comment by rensir** [comment]
确实有这个问题

**Comment by freakchick** [comment]
那你就要把数据库账号密码配对啊，都配错了，和系统有啥关系
