### ISSUE TITLE
关于sql运行结果不能展示全的

### ISSUE THREAD

**Issue by supergenge** [freakchick/DBApi#47]
![0bc6834ea91af747f9d54bc1e2df3b9](https://github.com/freakchick/DBApi/assets/27846806/44cc3e5f-129c-460b-88ca-d39f6af90184)
运行sql，下方的执行结果显示不全的问题

**Comment by supergenge** [comment]
而且不能滑动，不太友好

**Comment by supergenge** [comment]
版本号4.0.0

**Comment by freakchick** [comment]
4.0.1已经修复
